### ISSUE TITLE
AJAX requests not captured

### ISSUE THREAD

**Issue by 0x62** [madhurjain/gopee#1]
If you load a site like YouTube, which makes an AJAX request to `googleusercontent.com` (I believe), then it won't pass this through the proxy.

**Comment by ocrumbs** [comment]
googleusercontent.com isa different domain. proxy should only work the domain it requested for. Youtube in your example. Also Ajax requests need to be proxied browser config.

**Comment by 0x62** [comment]
In order to function as a proxy it has to be assumed that all websites except for the proxy are blocked. Videos for YouTube are not hosted at youtube.com, they're hosted at googleusercontent.com. In the same way, Facebook media is hosted at fbcdn.com. Unless these requests go through a proxy too then it will not work as a proxy.

AJAX requests can be captured through the proxy.

1) Injecting Javascript to handle them:

```
(function(open) {

    XMLHttpRequest.prototype.open = function(method, url, async, user, pass) {

        this.addEventListener("readystatechange", function() {
            console.log(this.readyState);
        }, false);

        open.call(this, method, url, async, user, pass);
    };

})(XMLHttpRequest.prototype.open);
```

2) Index referenced files on request and replace urls. For example use RegEx to find URLs, and replace them with `proxy.whatever/p/theurl`, so they are automatically proxied too.

You also have to proxy root relative urls (like `/ajax/test.php`), which can be done by catching all requests and 301 redirecting them via referrer.

**Comment by ocrumbs** [comment]
If you are concerned with ajax, then use [Tor](https://www.torproject.org/). It proxies all the request (incl ajax). Web proxies don't deal with ajax, because ajax request is directly made by the browser internals. So you need to configure your browser with proper proxy settings like the address and port of the proxy server.

**Comment by 0x62** [comment]
Not supporting AJAX makes a proxy effectively useless. As I said above (and provided two methods to do so), AJAX requests can be captured by the proxy. They're simply a Javascript request.

Picture the following on a site called `myproxy.com`, at address `myproxy.com/p/youtube.com`:

```
$.get('/ajax/comments.php'); // Do something with response, doesn't matter what
```

This will send a GET request to `myproxy.com/ajax/comments.php`. This file doesn't exist. Therefor, what you do it set a route in the index file for myproxy.com which captures routes which do not exist (written as pseudocode below):

```
if route.url not exist:
  301 redirect to referrer + route.url
else:
  render route.url
```

This allows you to render files which exist (`myproxy.com/css/style.css`), yet AJAX requests will be captured.

There's nothing special about AJAX that requires you to configure a proxy in the browser at all.

**Comment by ocrumbs** [comment]
I dont get it, how does the ajax GET request  is made to `myproxy.com/ajax/comments.php`? It should be `originalwebsite/ajax/comments.php` because the Ajax calls are made by the browser engine not user interactions. Unless ofcourse you are asking this library to parse js files and replace all the base address with `myproxy.com`. Javascript can be very complicated and its not easy to correctly parse without errors.

Also Ajax calls can still collect your local computer data which makes it unsafe to use scripts behind proxies anyways. But either way, you need to set your browser to explicitly use proxy server, if you need to do Ajax requests via proxies. I hope you understand what I am trying to convey here.

**Comment by 0x62** [comment]
AJAX requests are commonly used with root relative or relative URL schemes. Therefor, a Javascript file from `originalsite.com/js/app.js` which made an AJAX request to `/ajax/comments.php` would actually make the request to `proxy.com/ajax/comments.php` as XMLHttpRequest doesn't care about what domain should be used, it uses the domain in the navigator.

**Comment by madhurjain** [comment]
@0x62 @denmaradi AJAX requests are being captured now. Please check and let me know ?

http://go-gopee.rhcloud.com/
